controller_list:
  - name: fake_right_arm_controller
    joints:
      - $(arg prefix)right_arm_shoulder_pan_joint
      - $(arg prefix)right_arm_shoulder_lift_joint
      - $(arg prefix)right_arm_elbow_joint
      - $(arg prefix)right_arm_wrist_1_joint
      - $(arg prefix)right_arm_wrist_2_joint
      - $(arg prefix)right_arm_wrist_3_joint
  - name: fake_left_arm_controller
    joints:
      - $(arg prefix)left_arm_shoulder_pan_joint
      - $(arg prefix)left_arm_shoulder_lift_joint
      - $(arg prefix)left_arm_elbow_joint
      - $(arg prefix)left_arm_wrist_1_joint
      - $(arg prefix)left_arm_wrist_2_joint
      - $(arg prefix)left_arm_wrist_3_joint
initial:  # Define initial robot poses.
  - group: right_arm
    pose: init
  - group: left_arm
    pose: init
