front_left_wheel_traction_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: rbsherpa_hl_front_left_wheel_traction_joint

front_left_wheel_steer_joint_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_front_left_wheel_steer_joint

front_right_wheel_traction_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: rbsherpa_hl_front_right_wheel_traction_joint

front_right_wheel_steer_joint_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_front_right_wheel_steer_joint

back_left_wheel_traction_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: rbsherpa_hl_back_left_wheel_traction_joint

back_left_wheel_steer_joint_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_back_left_wheel_steer_joint

back_right_wheel_traction_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: rbsherpa_hl_back_right_wheel_traction_joint

back_right_wheel_steer_joint_controller:
  type: position_controllers/JointPositionController
  joint: rbsherpa_hl_back_right_wheel_steer_joint


base_controller:
  type: rbsherpa_hl_omni_controller/RbSherpaHlOmniController
  traction:
    front_right:
      joint_name: rbsherpa_hl_front_right_wheel_traction_joint
      max_speed: 20.0 # rad/s
    front_left:
      joint_name: rbsherpa_hl_front_left_wheel_traction_joint
      max_speed: 20.0 # rad/s
    back_right:
      joint_name: rbsherpa_hl_back_right_wheel_traction_joint
      max_speed: 20.0 # rad/s
    back_left:
      joint_name: rbsherpa_hl_back_left_wheel_traction_joint
      max_speed: 20.0 # rad/s
  steer:
    front_right:
      joint_name: rbsherpa_hl_front_right_wheel_steer_joint
      min_angle: -3.1 # rads
      max_angle: 3.1
    front_left:
      joint_name: rbsherpa_hl_front_left_wheel_steer_joint
      min_angle: -3.1 # rads
      max_angle: 3.1
    back_right:
      joint_name: rbsherpa_hl_back_right_wheel_steer_joint
      min_angle: -3.1 # rads
      max_angle: 3.1
    back_left:
      joint_name: rbsherpa_hl_back_left_wheel_steer_joint
      min_angle: -3.1 # rads
      max_angle: 3.1
  linear_speed_limit: 2.8
  linear_acceleration_limit: 2.0
  angular_speed_limit: 2.0
  angular_acceleration_limit: 2.0
  odom_frame: rbsherpa_hl_odom
  robot_base_frame: rbsherpa_hl_base_footprint
  odom_broadcast_tf: true
  odom_topic: odom
  wheel_base: 1.244 #from cad # 1.244 or 1.42
  track_width: 0.734 #from cad # 0.734 or 0.72
  wheel_diameter: 0.315 #  from cad
  cmd_watchdog_duration: 0.2
  odom_publish_frequency: 100
  motion_odometry: true
  imu_topic: 'imu/data'


joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0

joint_read_command_controller:
    type: joint_read_command_controller/JointReadCommandController 
    publish_rate: 100.0

# Settings for ros_control hardware interface
hardware_interface:
  joints:
     - rbsherpa_hl_front_right_wheel_steer_joint
     - rbsherpa_hl_front_left_wheel_steer_joint
     - rbsherpa_hl_back_right_wheel_steer_joint
     - rbsherpa_hl_back_left_wheel_steer_joint
     - rbsherpa_hl_front_right_wheel_traction_joint
     - rbsherpa_hl_front_left_wheel_traction_joint
     - rbsherpa_hl_back_right_wheel_traction_joint
     - rbsherpa_hl_back_left_wheel_traction_joint
