# This is intended to be used in case the gripper is mimetic.
# The controller joint must be the master joint. 
gripper:
  type: position_controllers/JointTrajectoryController
  joints: 
    - $(arg prefix)gripper_finger_left_joint